// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /home/nicofico/user_files/unibo/LabEM/./resonanceType.hpp;
#pragma link C++ defined_in "/home/nicofico/user_files/unibo/LabEM/./resonanceType.cpp";

#endif
