#include <TFile.h>

void setStyle() {
  gROOT->SetStyle("Plain");
  gStyle->SetPalette(57);
  gStyle->SetOptTitle(1);
  gStyle->SetOptFit(1);

  // Don't display canvases on screen
  gROOT->SetBatch(kTRUE);
}

void setFitStyle(TF1* f) {
  f->SetLineColor(kRed);
  f->SetLineStyle(1);
  f->SetLineWidth(2);
}

void histos() {
  auto* histosFile{new TFile{"histos.root"}};

  auto* hParticleTypes{dynamic_cast<TH1I*>(histosFile->Get("hParticleTypes"))};
  auto* hPhi{dynamic_cast<TH1D*>(histosFile->Get("hPhi"))};
  auto* hTheta{dynamic_cast<TH1D*>(histosFile->Get("hTheta"))};
  auto* hImpulse{dynamic_cast<TH1D*>(histosFile->Get("hImpulse"))};
  auto* hTransverseImpulse{
      dynamic_cast<TH1D*>(histosFile->Get("hTransverseImpulse"))};
  auto* hEnergy{dynamic_cast<TH1D*>(histosFile->Get("hEnergy"))};
  auto* hInvMass{dynamic_cast<TH1D*>(histosFile->Get("hInvMass"))};
  auto* hInvMassSameSign{
      dynamic_cast<TH1D*>(histosFile->Get("hInvMassSameSign"))};
  auto* hInvMassDiscSign{
      dynamic_cast<TH1D*>(histosFile->Get("hInvMassDiscSign"))};
  auto* hInvMassPiKSame{
      dynamic_cast<TH1D*>(histosFile->Get("hInvMassPiKSame"))};
  auto* hInvMassPiKDisc{
      dynamic_cast<TH1D*>(histosFile->Get("hInvMassPiKDisc"))};
  auto* hInvMassDecayProd{
      dynamic_cast<TH1D*>(histosFile->Get("hInvMassDecayProd"))};

  // Difference of histos
  auto* hInvMassSubAll{new TH1D{"hInvMassSubAll",
                                "Invariant mass (difference between same & "
                                "discordant signs - All particles)",
                                500, 0., 5.}};
  hInvMassSubAll->GetXaxis()->SetTitle("Invariant mass (GeV/c^2)");
  hInvMassSubAll->GetYaxis()->SetTitle("Entries");
  hInvMassSubAll->Add(hInvMassDiscSign, hInvMassSameSign, 1., -1.);

  auto* hInvMassSubPiK{new TH1D{
      "hInvMassSubPiK",
      "Invariant mass (difference between same & discordant signs - pi-K)", 500,
      0., 5.}};
  hInvMassSubPiK->GetXaxis()->SetTitle("Invariant mass (GeV/c^2)");
  hInvMassSubPiK->GetYaxis()->SetTitle("Entries");
  hInvMassSubPiK->Add(hInvMassPiKDisc, hInvMassPiKSame, 1., -1.);

  // Particle types generation data

  const std::array<std::string, 7> particleTypes{"pi+", "pi-", "K+", "K-",
                                                 "p+",  "p-",  "K*"};

  std::cout << "\nParticles generated by type:\n";
  for (size_t i{0}; i < particleTypes.size(); ++i) {
    std::cout << particleTypes[i] << ": "
              << hParticleTypes->GetBinContent(i + 1) << " +/- "
              << hParticleTypes->GetBinError(i + 1) << '\n';
  }
  std::cout << std::endl;

  // Style
  setStyle();

  auto* ThetaUniform{new TF1{"ThetaUniform", "pol0", 0., TMath::Pi()}};
  setFitStyle(ThetaUniform);
    ThetaUniform->SetParameter(0, 20'000);
	hTheta->Fit(ThetaUniform, "Q"); // suppresses output messages
	std::cout << "Theta fit: " << ThetaUniform->GetParameter(0) << " +/- " << ThetaUniform->GetParError(0) << '\n';
	std::cout << "Theta chi2/NDF: " << ThetaUniform->GetChisquare() / ThetaUniform->GetNDF() << '\n';
	std::cout << "Theta chi2 prob: " << ThetaUniform->GetProb() << '\n';
	std::cout << "Theta NDF: " << ThetaUniform->GetNDF() << '\n';
	std::cout << "Theta chi2: " << ThetaUniform->GetChisquare() << '\n';
    std::cout << std::endl;

    auto* PhiUniform{new TF1{"PhiUniform", "pol0", 0., TMath::TwoPi()}};
	setFitStyle(PhiUniform);
	PhiUniform->SetParameter(0, 20'000);
	hPhi->Fit(PhiUniform, "Q");
	std::cout << "Phi fit: " << PhiUniform->GetParameter(0) << " +/- " << PhiUniform->GetParError(0) << '\n';
	std::cout << "Phi chi2/NDF: " << PhiUniform->GetChisquare() / PhiUniform->GetNDF() << '\n';
	std::cout << "Phi chi2 prob: " << PhiUniform->GetProb() << '\n';
	std::cout << "Phi NDF: " << PhiUniform->GetNDF() << '\n';
	std::cout << "Phi chi2: " << PhiUniform->GetChisquare() << '\n';
    std::cout << std::endl;

    auto* PulseExpo{new TF1{"PulseExpo", "expo", 0., 5.}};
	setFitStyle(PulseExpo);
	PulseExpo->SetLineWidth(1);
	PulseExpo->SetParameter(0, 1.);
	PulseExpo->SetParameter(1, 1.);
	hImpulse->Fit(PulseExpo, "Q");
	std::cout << "Impulse fit amplitude: " << PulseExpo->GetParameter(0) << " +/- " << PulseExpo->GetParError(0)
			  << '\n';
	std::cout << "Impulse fit decay: " << PulseExpo->GetParameter(1) << " +/- " << PulseExpo->GetParError(1)
			  << '\n';
	std::cout << "Impulse chi2/NDF: " << PulseExpo->GetChisquare() / PulseExpo->GetNDF() << '\n';
	std::cout << "Impulse chi2 prob: " << PulseExpo->GetProb() << '\n';
	std::cout << "Impulse NDF: " << PulseExpo->GetNDF() << '\n';
	std::cout << "Impulse chi2: " << PulseExpo->GetChisquare() << '\n';
    std::cout << std::endl;

    auto* fGausAll{new TF1{"fGausAll", "gausn", 0., 5.}};
	setFitStyle(fGausAll);
	fGausAll->SetParameter(0, 800.);
	fGausAll->SetParameter(1, 0.9);
	fGausAll->SetParameter(2, 0.05);
	hInvMassSubAll->Fit(fGausAll, "Q");
	for (int i{0}; i < 3; ++i)
	{
		std::cout << "GausAll fit parameter " << i << ": " << fGausAll->GetParameter(i) << " +/- "
				  << fGausAll->GetParError(i) << '\n';
	}
	std::cout << "GausAll chi2/NDF: " << fGausAll->GetChisquare() / fGausAll->GetNDF() << '\n';
	std::cout << "GausAll chi2 prob: " << fGausAll->GetProb() << '\n';
	std::cout << "GausAll NDF: " << fGausAll->GetNDF() << '\n';
	std::cout << "GausAll chi2: " << fGausAll->GetChisquare() << '\n';
    std::cout << std::endl;

	auto* fGausPiK{new TF1{"fGausPiK", "gausn", 0., 5.}};
	setFitStyle(fGausPiK);
	fGausPiK->SetParameter(0, 800.);
	fGausPiK->SetParameter(1, 0.9);
	fGausPiK->SetParameter(2, 0.05);
	hInvMassSubPiK->Fit(fGausPiK, "Q");
	for (int i{0}; i < 3; ++i)
	{
		std::cout << "GausPiK fit parameter " << i << ": " << fGausPiK->GetParameter(i) << " +/- "
				  << fGausPiK->GetParError(i) << '\n';
	}
	std::cout << "GausPiK chi2/NDF: " << fGausPiK->GetChisquare() / fGausPiK->GetNDF() << '\n';
	std::cout << "GausPiK chi2 prob: " << fGausPiK->GetProb() << '\n';
	std::cout << "GausPiK NDF: " << fGausPiK->GetNDF() << '\n';
	std::cout << "GausPiK chi2: " << fGausPiK->GetChisquare() << '\n';
    std::cout << std::endl;

	auto* fGausDecayProd{new TF1{"fGausDecayProd", "gausn", 0., 5.}};
	setFitStyle(fGausDecayProd);
	fGausDecayProd->SetLineWidth(1);
	fGausDecayProd->SetParameter(0, 800.);
	fGausDecayProd->SetParameter(1, 0.9);
	fGausDecayProd->SetParameter(2, 0.05);
	hInvMassDecayProd->Fit(fGausDecayProd, "Q");
	for (int i{0}; i < 3; ++i)
	{
		std::cout << "GausDecayProd fit parameter " << i << ": " << fGausDecayProd->GetParameter(i) << " +/- "
				  << fGausDecayProd->GetParError(i) << '\n';
	}
	std::cout << "GausDecayProd chi2/NDF: " << fGausDecayProd->GetChisquare() / fGausDecayProd->GetNDF() << '\n';
	std::cout << "GausDecayProd chi2 prob: " << fGausDecayProd->GetProb() << '\n';
	std::cout << "GausDecayProd NDF: " << fGausDecayProd->GetNDF() << '\n';
	std::cout << "GausDecayProd chi2: " << fGausDecayProd->GetChisquare() << '\n';
    std::cout << std::endl;


    // Draw each histo in a canvas
	std::vector<TCanvas*> canvases;

	canvases.push_back(new TCanvas{"cParticleTypes", "Particle types", 800, 600});
	hParticleTypes->Draw();
	canvases.push_back(new TCanvas{"cPhi", "Phi", 800, 600});
	hPhi->Draw();
	canvases.push_back(new TCanvas{"cTheta", "Theta", 800, 600});
	hTheta->Draw();
	canvases.push_back(new TCanvas{"cImpulse", "Impulse", 800, 600});
	hImpulse->Draw();
	canvases.push_back(new TCanvas{"cTransverseImpulse", "Transverse impulse", 800, 600});
	hTransverseImpulse->Draw();
	canvases.push_back(new TCanvas{"cEnergy", "Energy", 800, 600});
	hEnergy->Draw();
	canvases.push_back(new TCanvas{"cInvMass", "Invariant mass", 800, 600});
	hInvMass->Draw();
	canvases.push_back(new TCanvas{"cInvMassSameSign", "Invariant mass same sign", 800, 600});
	hInvMassSameSign->Draw();
	canvases.push_back(new TCanvas{"cInvMassDiscSign", "Invariant mass disc sign", 800, 600});
	hInvMassDiscSign->Draw();
	canvases.push_back(new TCanvas{"cInvMassPiKSame", "Invariant mass pi K same", 800, 600});
	hInvMassPiKSame->Draw();
	canvases.push_back(new TCanvas{"cInvMassPiKDisc", "Invariant mass pi K disc", 800, 600});
	hInvMassPiKDisc->Draw();
	canvases.push_back(new TCanvas{"cInvMassDecayProd", "Invariant mass decay products", 800, 600});
	hInvMassDecayProd->Draw();
	canvases.push_back(new TCanvas{"cInvMassSubAll", "Invariant mass sub all", 800, 600});
	hInvMassSubAll->Draw();
	canvases.push_back(new TCanvas{"cInvMassSubPiK", "Invariant mass sub pi K", 800, 600});
	hInvMassSubPiK->Draw();

    // Save each canvas as pdf, C and root file
	system("mkdir -p build/pdf");
	system("mkdir -p build/C");
	system("mkdir -p build/root");
	for (auto* canvas : canvases)
	{
    canvas->Print(
        (std::string{"build/pdf/"} + canvas->GetName() + ".pdf").c_str());
    canvas->Print((std::string{"build/C/"} + canvas->GetName() + ".C").c_str());
    canvas->Print(
        (std::string{"build/root/"} + canvas->GetName() + ".root").c_str());
	}
}